[package]
name = "sapling-gui"
version.workspace = true
edition.workspace = true

[dependencies]
kasuari.workspace = true
raylib.workspace = true
sapling-app.workspace = true
sapling-gui-macro.workspace = true
anyhow.workspace = true
