[package]
name = "sapling-gui"
version.workspace = true
edition.workspace = true

[dependencies]
raylib.workspace = true
sapling-app.workspace = true
anyhow.workspace = true
petgraph.workspace = true
