[package]
name = "sapling-app"
version.workspace = true
edition.workspace = true

[dependencies]
sapling-data-model.workspace = true
sapling-serialization.workspace = true
sapling-query-engine.workspace = true
